### PR TITLE
Fix "Response length returned exceeded limit" error

### LINKED ISSUE #289: Response length returned exceeded our limit for reading for request
Hi @asgrim, 

We deployed scout APM into our Production laravel application but we continuously see the following error in the logs for every request that is hitting the API:

```
[2022-09-26 17:52:40] production.NOTICE: [Scout] Response length returned (1667509603) exceeded our limit for reading (10000000) for Scoutapm\Events\Request\Request. Address was: tcp://127.0.0.1:6590
```

Is this a bug? or how can we fix the problem?

Thanks

### PR DESCRIPTION
**Pull request by asgrim**
Fixes #289

### CODE REVIEW

File: src/Connector/Exception/FailedToSendCommand.php [hunk 1]
```diff
@@ -149,15 +149,24 @@ public static function fromTooLargeResponseLength(
     }
 
     /** @param resource $socketResource */
-    public static function readingResponseContentFromSocket(Command $attemptedCommand, $socketResource, ConnectionAddress $connectionAddress): self
-    {
+    public static function readingResponseContentFromSocket(
```
Comment (asgrim) [inline src/Connector/Exception/FailedToSendCommand.php:152]: This is indeed a minor BC break:

```
 # Changed
 - [BC] The number of required arguments for Scoutapm\Connector\Exception\FailedToSendCommand::readingResponseContentFromSocket() increased from 3 to 6
 - [BC] The parameter $socketResource of Scoutapm\Connector\Exception\FailedToSendCommand::readingResponseContentFromSocket() changed from no type to a non-contravariant int
 - [BC] The parameter $connectionAddress of Scoutapm\Connector\Exception\FailedToSendCommand::readingResponseContentFromSocket() changed from Scoutapm\Connector\ConnectionAddress to a non-contravariant int
```

Although it is highly unlikely to affect downstream consumers of the library, since this named constructor for the exception is likely only useful internally (although "catching" the exception is not BC broken as such, although the message has changed slightly. Just something to be aware of, but the impact on consumers is expected to be very minimal.
