### PR TITLE
Suppress backtraces for Controller/Middleware/Job spans

### LINKED ISSUE #94: Don't capture backtraces for Controller and Middleware
Similar feature in python: https://github.com/scoutapp/scout_apm_python/blob/master/src/scout_apm/core/tracked_request.py#L207

We don't want to spend effort capturing backtraces that don't add any value. Controller and Middleware will always be a large stack of internal-to-the-framework frames, and nothing customer actionable.

### PR DESCRIPTION
**Pull request by asgrim**
Fixes #94

### CODE REVIEW

File: src/Events/Span/Span.php [hunk 1]
```diff
@@ -65,6 +74,22 @@ public function parent() : CommandWithChildren
...
+            return;
+        }
+
+        $this->tag(Tag::TAG_STACK_TRACE, Backtrace::capture());
+    }
+
+    private function isControllerOrMiddleware() : bool
+    {
+        return strpos($this->name, self::INSTRUMENT_CONTROLLER) === 0
+            || strpos($this->name, self::INSTRUMENT_MIDDLEWARE) === 0;
```
Comment (cschneid) [inline src/Events/Span/Span.php]: We don't have Job support yet in the agent, but may as well add it here anyway, since the constant is there, and we'll get to it soon enough.
